# Generated by Django 5.0.7 on 2024-07-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_slider',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
