# Generated by Django 5.0.7 on 2024-07-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_nav_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav_slider',
            name='link',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
