# Generated by Django 5.0.7 on 2024-08-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_additional_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.PositiveBigIntegerField(default=True, null=True)),
                ('image', models.ImageField(upload_to='image/offer')),
            ],
        ),
    ]
