# Generated by Django 5.0.7 on 2024-08-17 06:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_alter_additional_images_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additional_images',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='additional_information',
            name='about',
        ),
        migrations.RemoveField(
            model_name='additional_information',
            name='title',
        ),
        migrations.AddField(
            model_name='additional_images',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='additional_images/'),
        ),
        migrations.AddField(
            model_name='additional_images',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='additional_images/'),
        ),
        migrations.AddField(
            model_name='additional_information',
            name='additional_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
