# Generated by Django 5.0.7 on 2024-08-17 08:11

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_remove_additional_information_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('Featured_image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping1',
            field=image_cropping.fields.ImageRatioField('image1', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping1'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping2',
            field=image_cropping.fields.ImageRatioField('image2', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping2'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping3',
            field=image_cropping.fields.ImageRatioField('image3', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Featured_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='additional_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='additional_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='additional_images/'),
        ),
    ]
