# Generated by Django 5.0.7 on 2024-08-17 09:04

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_product_cropping_product_cropping1_product_cropping2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cropping1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cropping2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cropping3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.AlterField(
            model_name='product',
            name='Featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.CreateModel(
            name='additional_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='additional_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='additional_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='additional_images/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.product')),
            ],
        ),
        migrations.CreateModel(
            name='additional_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.product')),
            ],
        ),
    ]
