# Generated by Django 5.0.7 on 2024-08-20 06:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional_information',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='additional_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='additional_images',
        ),
        migrations.DeleteModel(
            name='additional_information',
        ),
    ]
