# Generated by Django 5.0.7 on 2024-08-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0020_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
