# Generated by Django 5.0.7 on 2024-09-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0022_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='razorpay_order_id',
        ),
    ]
