# Generated by Django 5.0.7 on 2024-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0032_color_size_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
