# Generated by Django 5.0.7 on 2024-08-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000018C8A3F5EE0>', max_length=200),
        ),
    ]
