# Generated by Django 5.0.7 on 2024-09-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0037_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001B399951300>', max_length=200),
        ),
    ]
